defaults: &defaults
  adapter: postgresql
  pool: 12
  timeout: 10000

test:
  <<: *defaults
  database: squirrel-test
  host: 127.0.0.1
  min_messages: WARNING

development:
  <<: *defaults
  database: squirrel-development
  host: 127.0.0.1

production:
  <<: *defaults
  database: squirrel-production
