# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5a28440cfc401934261b82b9f7bb73ad38c25d14c987b969a425dffac2c9f0d4da43a17f4800dc07002a0d8d14e45c963cf418999a68552eb8fd4609c998a2c

test:
  secret_key_base: c96456914c85ca4ac33c75b362872a079b7e3486fd6b7b07e53bfc6c520bdf0bc9abd1bb6f76fd2845dc7bb9fd436227b5120929340fd604cec72ac5cf48d076

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
